### ISSUE TITLE
安装自身框架报错

### ISSUE THREAD

**Issue by luo-xin** [Tencent/FAutoTest#12]
![error](https://user-images.githubusercontent.com/34369480/47080511-bddb4480-d23a-11e8-9435-196dbd8b660b.jpeg)

**Comment by Jaggerer** [comment]
1.确认是否使用python2.7，本框架暂不支持python3。
2.python版本是否过老，建议升级到2.7.15版本。

**Comment by magohome** [comment]
python 版本 2.7.10 是否支持，


报错如下
 pip install ./fastAutoTest-2.2.3-py2-none-any.whl
The directory '/Users/babyfs/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/babyfs/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./fastAutoTest-2.2.3-py2-none-any.whl
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/download.py", line 823, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/download.py", line 728, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/utils/misc.py", line 582, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/Library/Python/2.7/site-packages/pip-18.1-py2.7.egg/pip/_internal/utils/misc.py", line 467, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
