### ISSUE TITLE
可以增加支持企业微信么？

### ISSUE THREAD

**Issue by metoto** [Tencent/FAutoTest#13]
目前有项目在使用企业微信的开发，但是今天试了一下还不能支持企业微信，这个是因为企业微信本身的问题么？

**Comment by metoto** [comment]
Error in sys.excepthook:
Traceback (most recent call last):
  File "E:\FAutoTest-master\fastAutoTest\utils\vmhook.py", line 48, in _handleUncaughtException
    raise Exception(exctype)
Exception: <type 'exceptions.RuntimeError'>

Original exception was:
Traceback (most recent call last):
  File "E:/FAutoTest-master/sample/HYK_TestDemo.py", line 17, in <module>
    h5Driver.initDriver()
  File "E:\FAutoTest-master\fastAutoTest\core\h5\h5Engine.py", line 70, in initDriver
    url = self._urlFetcher.fetchWebSocketDebugUrl()
  File "E:\FAutoTest-master\fastAutoTest\core\h5\h5WebSocketDebugUrlFetcher.py", line 37, in fetchWebSocketDebugUrl
    self._fetchInner()
  File "E:\FAutoTest-master\fastAutoTest\core\h5\h5WebSocketDebugUrlFetcher.py", line 55, in _fetchInner
    self._webSocketDebugUrl = self._fetchWebSocketDebugUrl(self._localForwardPort)
  File "E:\FAutoTest-master\fastAutoTest\core\h5\h5WebSocketDebugUrlFetcher.py", line 162, in _fetchWebSocketDebugUrl
    raise RuntimeError(errorMsg)
RuntimeError: 在执行脚本前，先进入H5页面

Process finished with exit code 1
