### ISSUE TITLE
demo运行小程序的时候报错

### ISSUE THREAD

**Issue by xuming2860** [Tencent/FAutoTest#16]
from fastAutoTest.core.wx.wxEngine import WxDriver
import os
# 进入企鹅医典小程序
if __name__ == '__main__':
    wxDriver = WxDriver()

    wxDriver.initDriver()
    # 点击全部疾病
    wxDriver.clickElementByXpath('/html/body/div/div[1]/div[2]/div[1]/a')
    wxDriver.clickFirstElementByText('肺癌')
    wxDriver.returnLastPage()
    wxDriver.returnLastPage()
    # 截图
    dirPath = os.path.split(os.path.realpath(__file__))[0]
    PIC_SRC = os.path.join(dirPath, 'pic.png')
    wxDriver.d.screenshot(PIC_SRC)
    wxDriver.close()

上面是demo中运行小程序的代码，我连接了OPPO手机之后，先打开了腾讯医典，然后运行代码，但是报错如下：
Traceback (most recent call last):
  File "C:/Users/charles/Downloads/FAutoTest-master/FAutoTest-master/sample/XcqDemo.py", line 17, in <module>
    wxDriver.initDriver()
  File "C:\Users\charles\Downloads\FAutoTest-master\FAutoTest-master\fastAutoTest\core\wx\wxEngine.py", line 64, in initDriver
    url = self._urlFetcher.fetchWebSocketDebugUrl()
  File "C:\Users\charles\Downloads\FAutoTest-master\FAutoTest-master\fastAutoTest\core\wx\wxWebSocketDebugUrlFetcher.py", line 64, in fetchWebSocketDebugUrl
    self._fetchInner()
  File "C:\Users\charles\Downloads\FAutoTest-master\FAutoTest-master\fastAutoTest\core\wx\wxWebSocketDebugUrlFetcher.py", line 77, in _fetchInner
    pid = WxWebSocketDebugUrlFetcher._fetchWeixinToolsProcessPid(device=self._device)
  File "C:\Users\charles\Downloads\FAutoTest-master\FAutoTest-master\fastAutoTest\core\wx\wxWebSocketDebugUrlFetcher.py", line 100, in _fetchWeixinToolsProcessPid
    raise RuntimeError(errorMsg)
**RuntimeError: 获取小程序pid失败，请检查是否在小程序首屏进行初始化**

我一段一段代码进行排查之后，发现wxWebSocketDebugUrlFetcher.py，这个文件中会在cmd中运行一串命令**adb shell cat /proc/net/unix | findstr webview_devtools_remote_%s**

而代码中是这么写的：
webviewCmd = _ADB_GET_WEBVIEW_TOOLS_CMD[osName] % (pid)
        # 验证是否启动了小程序webview
        try:
            webStdout, webStdError = runCommand(AdbHelper.specifyDeviceOnCmd(webviewCmd, device))
            print("--------"+webStdout)
        except:
            print("出错")
            errorMsg = ErrorMsgManager().errorCodeToString(ERROR_CODE_NOT_ENTER_XCX)
            raise RuntimeError(errorMsg)
        return pid

也就是说运行这个命令错误，直接抛出异常的。
这个命令在你的INITERROR.md中并没有提到，我想问一下这个应该怎么解决呢？
能否不运行，直接把split得到的pid直接返回回去呢？

**Comment by Yiliayan** [comment]
我也遇到了这个问题。。。同求解决办法

**Comment by songjinhua** [comment]
同求解决办法阿，赶脚这个框架还不成熟的样子，demo都没法跑怎么用阿

**Comment by liuln** [comment]
我也遇到了相同的问题，请问有解决办法了么？

**Comment by Yiliayan** [comment]
我重新装了微信6.6.3就可以了，好像跟机型和微信版本有关，我目前只有一个手机可以

**Comment by liuln** [comment]
我的问题也解决了，我用的是OPPO A5的测试手机，用adb命令获取到activity有两个，如附件所示：
而我们的FAT获取到的是前一个，我稍微变动了一下wxWebSocketDebugUrlFetcher.py下的 _fetchWeixinToolsProcessPid函数，经pid由pid = strlist[1].split("\r\n")[0]变为pid = strlist[len(strlist)-1].split("\r\n")[0]，问题成功解决了。
